/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package endodump2strava.strava.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DetailedAthlete (
  /* The unique identifier of the athlete */
  id: Option[Long] = None,
  /* Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\" */
  resourceState: Option[Int] = None,
  /* The athlete's first name. */
  firstname: Option[String] = None,
  /* The athlete's last name. */
  lastname: Option[String] = None,
  /* URL to a 62x62 pixel profile picture. */
  profileMedium: Option[String] = None,
  /* URL to a 124x124 pixel profile picture. */
  profile: Option[String] = None,
  /* The athlete's city. */
  city: Option[String] = None,
  /* The athlete's state or geographical region. */
  state: Option[String] = None,
  /* The athlete's country. */
  country: Option[String] = None,
  /* The athlete's sex. */
  sex: Option[DetailedAthleteEnums.Sex] = None,
  /* Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription. */
  premium: Option[Boolean] = None,
  /* Whether the athlete has any Summit subscription. */
  summit: Option[Boolean] = None,
  /* The time at which the athlete was created. */
  createdAt: Option[DateTime] = None,
  /* The time at which the athlete was last updated. */
  updatedAt: Option[DateTime] = None,
  /* The athlete's follower count. */
  followerCount: Option[Int] = None,
  /* The athlete's friend count. */
  friendCount: Option[Int] = None,
  /* The athlete's preferred unit system. */
  measurementPreference: Option[DetailedAthleteEnums.MeasurementPreference] = None,
  /* The athlete's FTP (Functional Threshold Power). */
  ftp: Option[Int] = None,
  /* The athlete's weight. */
  weight: Option[Float] = None,
  /* The athlete's clubs. */
  clubs: Option[Seq[SummaryClub]] = None,
  /* The athlete's bikes. */
  bikes: Option[Seq[SummaryGear]] = None,
  /* The athlete's shoes. */
  shoes: Option[Seq[SummaryGear]] = None
) extends ApiModel

object DetailedAthleteEnums {

  type Sex = Sex.Value
  type MeasurementPreference = MeasurementPreference.Value
  object Sex extends Enumeration {
    val `M` = Value("M")
    val `F` = Value("F")
  }

  object MeasurementPreference extends Enumeration {
    val Feet = Value("feet")
    val Meters = Value("meters")
  }

}

