/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package endodump2strava.strava.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class StreamSet (
  time: Option[TimeStream] = None,
  distance: Option[DistanceStream] = None,
  latlng: Option[LatLngStream] = None,
  altitude: Option[AltitudeStream] = None,
  velocitySmooth: Option[SmoothVelocityStream] = None,
  heartrate: Option[HeartrateStream] = None,
  cadence: Option[CadenceStream] = None,
  watts: Option[PowerStream] = None,
  temp: Option[TemperatureStream] = None,
  moving: Option[MovingStream] = None,
  gradeSmooth: Option[SmoothGradeStream] = None
) extends ApiModel


